source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
target 'XiMaLaYaNav' do
inhibit_all_warnings!

pod 'JKCategories', '~> 1.6'
pod 'SDWebImage', '~> 4.3.3'
pod 'JSONModel', '~> 1.1.2'
pod 'Masonry', '~> 0.6.3'
pod 'YYWebImage', '~> 0.9.11'
pod 'POP+MCAnimate', '2.0.1'
pod 'ReactiveCocoa', '2.3.1'
end
